ciliatest/config/routes.rb
Ciliatest::Application.routes.draw do

  devise_for :clients, controllers: { sessions: 'clients/sessions' }

  root :to => 'site/home#index'

  namespace :site do
    get 'home', to: 'home#index' ##quando for ../home acessa /home/index
    resources :orders, only: [:index, :show, :new, :create]
    get 'clients', to: 'clients#index' ##quando for ../clients acessa /clients/index
    resources :clients
    get 'products', to: 'products#index' ##quando for ../clients acessa /clients/index
    resources :products
    namespace :home do
      resources :carts, only: [:index, :show, :new, :create, :edit, :update]
      resources :carts_products, only: [:edit, :update, :destroy]
    end
    resources :orders, only: [:index, :show, :new, :create]
    get 'checkouts', to: 'checkouts#index'
  end

end

ciliatest/app/models/cart.rb
class Cart < ActiveRecord::Base

  belongs_to :client
  has_many :cart_products
  has_many :products, through: :cart_products

  attr_accessible :products_attributes,
                  :client_attributes
end

ciliatest/app/models/cart_product.rb
class CartProduct < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart

  attr_accessible :product_attributes, :cart_attributes
end

ciliatest/app/models/client.rb
class Client < ActiveRecord::Base

  has_one :cart
  has_many :orders
  has_many :products, :through => :orders

  #validates
  validates :name, :email, presence:true


  #scopes


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :email,
                  :password,
                  :password_confirmation,
                  :name,
                  :born,
                  :cart_attributes,
                  :orders_attributes,
                  :products_attributes
end

ciliatest/app/models/demand.rb
class Demand < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart

  attr_accessible :product_attributes, :cart_attributes
end

ciliatest/app/models/order.rb
class Order < ActiveRecord::Base

  belongs_to :client
  has_many :products

  attr_accessible :client_attributes,
                  :products_attributes
end

ciliatest/app/models/product.rb
class Product < ActiveRecord::Base

  belongs_to :order
  has_many :cart_products
  has_many :carts, through: :cart_products

  validates :name, presence: true
  validates :price, numericality: { greater_than: 0 }

  #paperclip
   has_attached_file :picture, styles: { large: "432x240#", medium: "320x150#", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
   validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/

  #scopes
  #Listando x Produtos em ordem de criação
  scope :descending_order, -> (quantity = 10) { limit(quantity).order(created_at: :desc) }
  #Listando produtos do mais barato até o mais caro
  scope :descending_order_by_price, -> { order('id ASC').reorder('price_cents ASC') }
  #Retorna os objetos com nomes(categorias distintas)
  scope :select_distinct_name, -> { group(:name) }
  #seleciona apenas produtos com um nome(categoria)
  scope :select_all_products_name, -> ( name ) { where( name: name ) }
  #contando quanto produtos temos com o mesmo nome
  scope :count_all_products_name, -> ( name ) { where( name: name ).count }
  #procurando produto por nome
  scope :find_by_name, -> ( name ) { where("name LIKE ?", "%#{name}%" ) }
  #produtos validos
  scope :selling_products, -> { where( sold: false ) }

  # example
  # scope :descending_order, -> (quantity = 10) { limit(quantity).order(created_at: :desc) }

  # gem money-rails
  monetize :price_cents

  attr_accessible :description,
                  :name,
                  :price,
                  :price_cents,
                  :picture,
                  :carts_attributes,
                  :orders_attributes
end

ciliatest/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

ciliatest/app/controllers/site/checkouts_controller.rb
class Site::CheckoutsController < SiteController
  def index
    if current_client.cart.products.present? && current_client.cart.products.selling_products.present?
      @order_products = current_client.cart.products
    end
  end

end

ciliatest/app/controllers/site/clients_controller.rb
class Site::ClientsController < SiteController
  def index
    @clients = Client.all
  end

end

ciliatest/app/controllers/site/home_controller.rb
class Site::HomeController < SiteController

  def index
    # @products = Product.descending_order(10)
    @products = products_show(6, params[:term])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  private
    def products_show(page_qtd, params_search)
      @show = Product.paginate(:page => params[:page], :per_page => page_qtd)
                     .find_by_name(params_search).selling_products
    end

end

ciliatest/app/controllers/site/orders_controller.rb
class Site::OrdersController < SiteController

  def index
    @client_orders = current_client.orders
  end

  def show

  end

  def new
    if has_products
      # create order
      @final_order = Order.new
      #set sold value from cart products to order
      current_client.cart.products.collect { |p| p.sold = true }
      #remove itens from other carts
      drop_itens(current_client.cart.products)
      #set_order
      @final_order.products = current_client.cart.products
      @final_order.client = current_client
      if  @final_order.save
        #clear current_user cart
        current_client.cart.products.clear
        redirect_to site_home_path, notice: "O Pedido (#{@final_order.id}) foi computado com sucesso"
      else
        redirect_to request.referrer, alert: "O pedido (#{@final_order.id}) falhou"
      end
    else
      redirect_to request.referrer, alert: "Carrinho Vazio!!!"
    end
  end

  private

  def has_products
    current_client.cart.products.present?
  end

  def drop_itens(products)
    Cart.all.reject{|c| c == current_client.cart }.each do |cart|
      cart.products = cart.products - products
    end
  end

end

ciliatest/app/controllers/site/products_controller.rb
class Site::ProductsController < SiteController
  before_filter :set_product, :only => [:edit, :update, :destroy]
  def index
    # @products = Product.descending_order(10)
    @products = products_show(10, params[:term])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

    def new
      @product = Product.new
    end

    def create
      @product = Product.new(params[:product])

      if @product.save
        redirect_to site_products_path, notice: "O Produto (#{@product.name}) foi cadastrado com sucesso"
      else
        render :new
      end
    end

    def edit
      #set_product via before_filter
    end

    def update
      if @product.update_attributes(params[:product])
        redirect_to site_products_path, notice: "O Produto (#{@product.name}) foi atualizado com sucesso"
      else
        render :edit
      end
    end

    def destroy
      @product.destroy

      respond_to do |format|
        format.html {
          redirect_to site_products_path, notice: "Produto (#{@product.name}) excluido com sucesso!!"
        }
        format.json {
          head :no_content
        }
      end
    end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  def products_show(page_qtd, params_search)
    @show = Product.paginate(:page => params[:page], :per_page => page_qtd).
            find_by_name(params_search).selling_products
  end

end

ciliatest/app/controllers/site_controller.rb
class SiteController < ApplicationController
  before_filter :authenticate_client!
  layout "site"

end

ciliatest/app/helpers/application_helper.rb
module ApplicationHelper
end

ciliatest/app/helpers/site/checkouts_helper.rb
module Site::CheckoutsHelper
end

ciliatest/app/helpers/site/clients_helper.rb
module Site::ClientsHelper
end

ciliatest/app/helpers/site/home_helper.rb
module Site::HomeHelper
end

ciliatest/app/helpers/site/orders_helper.rb
module Site::OrdersHelper
end

ciliatest/app/helpers/site/products_helper.rb
module Site::ProductsHelper
end

ciliatest/app/helpers/site_helper.rb
module SiteHelper

  def products_on_cart
    unless current_client.cart.nil?
      @products_on_cart = current_client.cart.products
    end
  end

  def cart_count
    @cart_count = (current_client.cart.cart_products).count
  end

end

ciliatest/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ciliatest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

ciliatest/app/views/layouts/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">

  <button id="menu-toggle"><i class="material-icons">list</i></button>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  </button>

  <div id="info-site">
    <% if client_signed_in? %>
        <%= link_to('Logout', destroy_client_session_path, method: :delete, :class => "nav-link") %>
        <div class="order-cont shop">
          <button class="shop_car">
            <span class="o-c">
              <i class="material-icons">shopping_cart</i>
              <b><%= cart_count %></b>
            </span>
          </button>
          <%= render partial: 'layouts/shared/shopcart' %>
        </div>
        <%= link_to(current_client.email, '#', :class => "nav-name") %>
      <% else %>
        <%= link_to('Login', new_client_session_path, :class => "nav-link") %>
      <% end %>
  </div>
</nav>

ciliatest/app/views/layouts/shared/_notifications.html.erb
<% if notice %>
  <script>
    $(document).ready(function() {
      $.notify({
      message: '<%= notice %>'
    },{
      type: 'success',
      allow_dismiss: true,
      placement: {
        from: 'top',
        align: 'center'
      },
      delay: 2000,
      timer: 1000
      });
    });
  </script>
<% end %>
<% if alert %>
  <script>
    $(document).ready(function() {
      $.notify({
      message: '<%= alert %>'
    },{
      type: 'danger',
      allow_dismiss: true,
      placement: {
        from: 'top',
        align: 'center'
      },
      delay: 2000,
      timer: 1000
      });
    });
  </script>
<% end %>

ciliatest/app/views/layouts/shared/_shopcart.html.erb
<div id="shop_cont">
  <div class="title-cont">
   <b>Carrinho de compras:</b><button id="close_cont"><i class="material-icons">close</i></button>
  </div>
  <div class="body-cont">
    <% if current_client.cart.present? %>
        <% products_on_cart.each do |p| %>
          <div class="cart-item">
            <b>1x <%= p.name %></b>
            <small><%= humanized_money_with_symbol p.price %></small>
            <%= link_to site_home_carts_product_path(p), method: :delete, data: { confirm: "Tem certeza?" }, :class => "btn btn-danger btn-sm remove" do %>
              <i class="material-icons">close</i>
            <% end %>
          </div>
        <% end %>
    <% end %>
  </div>
  <div class="final-cont">
    <%= link_to "Finalizar Compra",  site_checkouts_path, :class => "btn btn-info btn-sm finalize" %>
  </div>
</div>

ciliatest/app/views/layouts/shared/_sidebar.html.erb
<!-- Sidebar -->
<div class="bg-light border-right" id="sidebar-wrapper">
  <div class="sidebar-heading">Loja Genérica</div>
  <div class="list-group list-group-flush">
    <%= link_to "Home", site_home_path, :action => "index", :class => "list-group-item list-group-item-action bg-light" %>
    <%= link_to "Clientes", site_clients_path, :action => "index", :class => "list-group-item list-group-item-action bg-light" %>
    <%= link_to "Produtos", site_products_path, :action => "index", :class => "list-group-item list-group-item-action bg-light" %>
    <%= link_to "Meus Produtos", site_orders_path, :action => "index", :class => "list-group-item list-group-item-action bg-light" %>

  </div>
</div>
<!-- /#sidebar-wrapper -->

ciliatest/app/views/layouts/site.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ciliatest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "site/home", :media => "all" %>
  <%= stylesheet_link_tag    "site/checkouts", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= render partial: 'layouts/shared/notifications' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="d-flex" id="wrapper">
  <%= stylesheet_link_tag    "site/home", :media => "all" %>
  <%= javascript_include_tag "site/home" %>
  <% if client_signed_in? %>
    <%= render partial: 'layouts/shared/sidebar', locals: {action: "Editar Administrador"} %>
  <% end  %>
    <!-- Page Content -->
    <div id="page-content-wrapper">
      <%= render partial: 'layouts/shared/navigation', locals: {action: "Editar Administrador"} %>
      <%= yield %>
    </div>
    <!-- /#page-content-wrapper -->
  </div>
</body>
</html>