ciliatest/config/routes.rb
Ciliatest::Application.routes.draw do

  devise_for :clients, controllers: { sessions: 'clients/sessions' }

  root :to => 'site/home#index'

  namespace :site do
    get 'home', to: 'home#index' ##quando for ../home acessa /home/index
    resources :orders, only: [:index, :show, :new, :create]
    get 'clients', to: 'clients#index' ##quando for ../clients acessa /clients/index
    resources :clients
    get 'products', to: 'products#index' ##quando for ../clients acessa /clients/index
    resources :products
    namespace :home do
      resources :carts, only: [:index, :show, :new, :create, :edit, :update]
      resources :carts_products, only: [:edit, :update, :destroy]
    end
    resources :orders, only: [:index, :show, :new, :create]
    get 'checkouts', to: 'checkouts#index'
  end

end

ciliatest/app/models/order.rb
class Order < ActiveRecord::Base

  belongs_to :client
  has_many :products

  attr_accessible :client_attributes,
                  :products_attributes
end

ciliatest/app/controllers/site/checkouts_controller.rb
class Site::CheckoutsController < SiteController
  def index
    if current_client.cart.products.present? && current_client.cart.products.selling_products.present?
      @order_products = current_client.cart.products
    end
  end

end

ciliatest/app/controllers/site/clients_controller.rb
class Site::ClientsController < SiteController
  def index
    @clients = Client.all
  end

end

ciliatest/app/controllers/site/home/carts_controller.rb
class Site::Home::CartsController < Site::HomeController
  before_filter :set_product, :only => [:edit, :update, :destroy]

  def index

  end

  def new

  end

end

ciliatest/app/controllers/site/home/carts_products_controller.rb
class Site::Home::CartsProductsController < Site::HomeController
  before_filter :set_cart_product_new, :only => [:edit, :update, :destroy]

  def new

  end

  def create

  end

  def edit
    #set_cart_product via before_filter
    if @cart_product.update_attributes(params[:cart_product])
      redirect_to request.referrer, notice: "O Produto (#{@cart_product.product.name}) foi adicionado ao carrinho com sucesso"
    else
      redirect_to request.referrer, notice: "Falha ao adicionar (#{@cart_product.product.name}) ao carrinho"
    end
  end

  def destroy
    #set_cart_product via before_filter
    @cart_product = current_client.cart.cart_products.where(product_id: params[:id])
    @cart_product[0].destroy
    respond_to do |format|
      format.html {
        redirect_to request.referrer, alert: "Produto (#{@cart_product[0].product.name}) excluido do carrinho"
      }
      format.json {
        head :no_content
      }
    end

  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_cart_product_new
    @cart_product = CartProduct.new
    @cart_product.cart = current_client.cart
    @cart_product.product = Product.find(params[:id])
  end
end

ciliatest/app/controllers/site/home_controller.rb
class Site::HomeController < SiteController

  def index
    # @products = Product.descending_order(10)
    @products = products_show(6, params[:term])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  private
    def products_show(page_qtd, params_search)
      @show = Product.paginate(:page => params[:page], :per_page => page_qtd)
                     .find_by_name(params_search).selling_products
    end

end

ciliatest/app/controllers/site/orders_controller.rb
class Site::OrdersController < SiteController

  def index
    @client_orders = current_client.orders
  end

  def show

  end

  def new
    if has_products
      # create order
      @final_order = Order.new
      #set sold value from cart products to order
      current_client.cart.products.collect { |p| p.sold = true }
      #remove itens from other carts
      drop_itens(current_client.cart.products)
      #set_order
      @final_order.products = current_client.cart.products
      @final_order.client = current_client
      if  @final_order.save
        #clear current_user cart
        current_client.cart.products.clear
        redirect_to site_home_path, notice: "O Pedido (#{@final_order.id}) foi computado com sucesso"
      else
        redirect_to request.referrer, alert: "O pedido (#{@final_order.id}) falhou"
      end
    else
      redirect_to request.referrer, alert: "Carrinho Vazio!!!"
    end
  end

  private

  def has_products
    current_client.cart.products.present?
  end

  def drop_itens(products)
    Cart.all.reject{|c| c == current_client.cart }.each do |cart|
      cart.products = cart.products - products
    end
  end

end

ciliatest/app/controllers/site/products_controller.rb
class Site::ProductsController < SiteController
  before_filter :set_product, :only => [:edit, :update, :destroy]
  def index
    # @products = Product.descending_order(10)
    @products = products_show(10, params[:term])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

    def new
      @product = Product.new
    end

    def create
      @product = Product.new(params[:product])

      if @product.save
        redirect_to site_products_path, notice: "O Produto (#{@product.name}) foi cadastrado com sucesso"
      else
        render :new
      end
    end

    def edit
      #set_product via before_filter
    end

    def update
      if @product.update_attributes(params[:product])
        redirect_to site_products_path, notice: "O Produto (#{@product.name}) foi atualizado com sucesso"
      else
        render :edit
      end
    end

    def destroy
      @product.destroy

      respond_to do |format|
        format.html {
          redirect_to site_products_path, notice: "Produto (#{@product.name}) excluido com sucesso!!"
        }
        format.json {
          head :no_content
        }
      end
    end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  def products_show(page_qtd, params_search)
    @show = Product.paginate(:page => params[:page], :per_page => page_qtd).
            find_by_name(params_search).selling_products
  end

end

ciliatest/app/controllers/site_controller.rb
class SiteController < ApplicationController
  before_filter :authenticate_client!
  layout "site"

end

ciliatest/app/helpers/site/checkouts_helper.rb
module Site::CheckoutsHelper
end

ciliatest/app/helpers/site/clients_helper.rb
module Site::ClientsHelper
end

ciliatest/app/helpers/site/home/carts_helper.rb
module Site::Home::CartsHelper
end

ciliatest/app/helpers/site/home/carts_products_helper.rb
module Site::Home::CartsProductsHelper
end

ciliatest/app/helpers/site/home_helper.rb
module Site::HomeHelper
end

ciliatest/app/helpers/site/orders_helper.rb
module Site::OrdersHelper
end

ciliatest/app/helpers/site/products_helper.rb
module Site::ProductsHelper
end

ciliatest/app/helpers/site_helper.rb
module SiteHelper

  def products_on_cart
    unless current_client.cart.nil?
      @products_on_cart = current_client.cart.products
    end
  end

  def cart_count
    @cart_count = (current_client.cart.cart_products).count
  end

end

ciliatest/app/views/site/orders/index.html.erb
<div id="order-page" class="container-fluid">
  <div class="row">
    <% if @client_orders.present? %>
      <% @client_orders.collect do |order| %>
        <div class="container-fluid order-cont">
          <h1><b>Pedido:#<%= order.id %></b> <small><%= I18n.l(order.created_at, format: :long) %></small> </h1>
          <div class="row">
            <% order.products.collect do |product| %>
              <div class="col-lg-6 col-sm-12">
                <div class="card order-product">
                  <%= image_tag product.picture(:medium) %>
                  <div class="card-body">
                    <h5 class="card-title"><%= product.name %></h5>
                    <b><%= humanized_money_with_symbol product.price %></b>
                    <p class="card-text"><%= truncate(product.description, length: 50) %></p>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    <% else %>
    <h1> Sem produtos computados! </h1>
    <% end %>
  </div>
</div>

ciliatest/app/views/site/orders/new.html.erb
<div class="order-cont">
  <div class="container-fluid">
    <div class="order-title">
      <h1><b>Pedido</b></h1>
    </div>
    <div class="order-list">
      <div class="order-item title">
        <b class="qtd">QTD</b>
        <p class="code">CÓDIGO</p>
        <picture>IMAGEM</picture>
        <p class="name">NOME</p>
        <p class="description">DESCRIÇÃO</p>
        <small class="price">PREÇO</small>
        <div class="blank-remove"></div>
      </div>
      <% @order_products.each do |item| %>
        <div class="order-item">
          <b class="qtd">1x</b>
          <p class="code"><%= item.id %></p>
          <picture><%= image_tag item.picture(:thumb) %></picture>
          <p class="name"><%= item.name %></p>
          <p class="description"><%= item.description %></p>
          <small class="price"><%= humanized_money_with_symbol item.price %></small>
          <div id="remove-item">
            <%= link_to site_home_carts_product_path(item), method: :delete, data: { confirm: "Tem certeza?" }, :class => "btn btn-sm btn-danger item-trash" do %>
              <i class="material-icons">close</i>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="order-check">
      <%= link_to "Voltar as Compras", site_home_path, :class => "btn btn-sm btn-secondary" %>
      <%= link_to "Finalizar Pedido", new_site_order_path, :class => "btn btn-sm btn-primary pull-right" %>
    </div>

  </div>
</div>